import Main from "../src/Layouts/Main/Main";

const head = {
  title: "Pettyt",
  content: "Generated by create next app",
};

export default function Home() {
  return <Main headers={head}>Hola</Main>;
}
